import Head from "next/head";
import { Inter } from "next/font/google";
import data from "../mock/data.json";
import dynamic from "next/dynamic";
import homeStyles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const Heatmap = dynamic(() => import("../components/Heatmap"), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>InsightsOS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className={homeStyles.chart}>
          <Heatmap data={data} />
        </div>
      </main>
    </>
  );
}
